kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: slo-monitor
subjects:
- kind: ServiceAccount
  name: slo-monitor
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: slo-monitor
  apiGroup: rbac.authorization.k8s.io

