kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: slo-monitor
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "watch", "list"]
