# ASSUMPTIONS:
# - This test is designed for 1-node cluster.

#Constants
{{$POD_COUNT := DefaultParam .POD_COUNT 100}}
{{$POD_THROUGHPUT := DefaultParam .POD_THROUGHPUT 5}}
{{$CONTAINER_IMAGE := DefaultParam .CONTAINER_IMAGE "k8s.gcr.io/pause:3.1"}}
{{$POD_STARTUP_LATENCY_THRESHOLD := DefaultParam .POD_STARTUP_LATENCY_THRESHOLD "5s"}}
{{$OPERATION_TIMEOUT := DefaultParam .OPERATION_TIMEOUT "15m"}}
{{$WINDOWS_NODE_TEST := DefaultParam .WINDOWS_NODE_TEST false}}

name: node-throughput
automanagedNamespaces: {{$POD_COUNT}}
tuningSets:
- name: UniformQPS
  qpsLoad:
    qps: {{$POD_THROUGHPUT}}
steps:
- measurements:
  {{if $WINDOWS_NODE_TEST}}
  - Identifier: WindowsResourceUsagePrometheus
    Method: WindowsResourceUsagePrometheus
    Params:
      action: start
  {{end}}
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: start
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = latency
      threshold: {{$POD_STARTUP_LATENCY_THRESHOLD}}
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: v1
      kind: ReplicationController
      labelSelector: group = latency
      operationTimeout: {{$OPERATION_TIMEOUT}}
- phases:
  - namespaceRange:
      min: 1
      max: {{$POD_COUNT}}
    replicasPerNamespace: 1
    tuningSet: UniformQPS
    objectBundle:
    - basename: latency-pod-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        Replicas: 1
        Group: latency
        Image: {{$CONTAINER_IMAGE}}
        WindowsNodeTest: {{$WINDOWS_NODE_TEST}}
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
  {{if $WINDOWS_NODE_TEST}}
  - Identifier: WindowsResourceUsagePrometheus
    Method: WindowsResourceUsagePrometheus
    Params:
      action: gather
  {{end}}
- phases:
  - namespaceRange:
      min: 1
      max: {{$POD_COUNT}}
    replicasPerNamespace: 0
    tuningSet: UniformQPS
    objectBundle:
    - basename: latency-pod-rc
      objectTemplatePath: rc.yaml
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
# Collect measurements
- measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather
- measurements:
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: gather
      enableViolations: true
      useSimpleLatencyQuery: true
      summaryName: APIResponsivenessPrometheus_simple
